/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bbms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aaliya
 */
public class BloodDonor extends javax.swing.JFrame {

    /**
     * Creates new form BloodDonor
     */
    public BloodDonor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        did = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dstate = new javax.swing.JComboBox<>();
        dblood = new javax.swing.JComboBox<>();
        dcity = new javax.swing.JComboBox<>();
        dinsert = new javax.swing.JButton();
        dcancel = new javax.swing.JButton();
        dlog = new javax.swing.JButton();
        dname = new javax.swing.JTextField();
        dbottle = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dcon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        did.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        did.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                didActionPerformed(evt);
            }
        });
        getContentPane().add(did);
        did.setBounds(270, 130, 160, 28);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Enter Your Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 150, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Enter Your ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 130, 150, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Blood Group");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 280, 140, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("State");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 180, 130, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("City");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 230, 120, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Bottles");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 330, 120, 22);

        dstate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dstate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karnataka", "Maharashtra", "Delhi", "Tamil Nadu", "Kerala", "Jammu & Kashmir" }));
        dstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dstateActionPerformed(evt);
            }
        });
        getContentPane().add(dstate);
        dstate.setBounds(270, 180, 160, 28);

        dblood.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dblood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "O+", "AB+", "AB-", "O-" }));
        dblood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbloodActionPerformed(evt);
            }
        });
        getContentPane().add(dblood);
        dblood.setBounds(270, 280, 160, 28);

        dcity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dcity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bangalore", "Mumbai", "Srinagar", "Cochi", "Chennai" }));
        getContentPane().add(dcity);
        dcity.setBounds(270, 230, 160, 28);

        dinsert.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        dinsert.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\insert.png")); // NOI18N
        dinsert.setText("INSERT");
        dinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinsertActionPerformed(evt);
            }
        });
        getContentPane().add(dinsert);
        dinsert.setBounds(10, 450, 140, 30);

        dcancel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        dcancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\reset.png")); // NOI18N
        dcancel.setText("RESET");
        dcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcancelActionPerformed(evt);
            }
        });
        getContentPane().add(dcancel);
        dcancel.setBounds(400, 450, 130, 30);

        dlog.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        dlog.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\log out.jpg")); // NOI18N
        dlog.setText("LOG OUT");
        dlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlogActionPerformed(evt);
            }
        });
        getContentPane().add(dlog);
        dlog.setBounds(360, 500, 170, 30);

        dname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(dname);
        dname.setBounds(270, 80, 160, 28);

        dbottle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dbottle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        dbottle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbottleActionPerformed(evt);
            }
        });
        getContentPane().add(dbottle);
        dbottle.setBounds(270, 330, 160, 28);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel9.setText("                                 DONOR FORM");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 550, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Contact");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 382, 150, 22);

        dcon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(dcon);
        dcon.setBounds(270, 379, 160, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\donor form.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 30, 550, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void didActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_didActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_didActionPerformed

    private void dbloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbloodActionPerformed

    private void dlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlogActionPerformed
       System.exit(0);
    }//GEN-LAST:event_dlogActionPerformed

    private void dstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dstateActionPerformed

    private void dinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinsertActionPerformed
       try
    {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/blood","root","");
            String sql="INSERT INTO donor VALUES(?,?,?,?,?,?)";
                PreparedStatement st=con.prepareStatement(sql);
                 st.setString(1, dname.getText()); 
                 st.setInt(2, Integer.parseInt(did.getText()));   
                st.setString(3, String.valueOf(dstate.getSelectedItem()));
                st.setString(4, String.valueOf(dcity.getSelectedItem()));
                 st.setString(5, String.valueOf(dblood.getSelectedItem()));
                st.setString(6, String.valueOf(dbottle.getSelectedItem()));
                 st.setString(7, dcon.getText());
                st.executeUpdate();
                JOptionPane.showMessageDialog(null," Donor Details Submitted Successfully");
    }                                       
catch (SQLException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
              
             
    }//GEN-LAST:event_dinsertActionPerformed

    private void dcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcancelActionPerformed
       dname.setText(null);
       did.setText(null);
       dcon.setText(null);
      
    }//GEN-LAST:event_dcancelActionPerformed

    private void dbottleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbottleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbottleActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       did.setText(Frame1.getID());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodDonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dblood;
    private javax.swing.JComboBox<String> dbottle;
    private javax.swing.JButton dcancel;
    private javax.swing.JComboBox<String> dcity;
    private javax.swing.JTextField dcon;
    private javax.swing.JTextField did;
    private javax.swing.JButton dinsert;
    private javax.swing.JButton dlog;
    private javax.swing.JTextField dname;
    private javax.swing.JComboBox<String> dstate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
