/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bbms;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aaliya
 */
public class Frame1 extends javax.swing.JFrame {
public static String userid="0";
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }
public void setID(String id)
{
    userid=id;
}
public static String getID()
{
    return userid;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        fname = new javax.swing.JLabel();
        femail = new javax.swing.JLabel();
        fback = new javax.swing.JLabel();
        fcancel = new javax.swing.JButton();
        feedback = new javax.swing.JButton();
        ftextn = new javax.swing.JTextField();
        ftextm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ftexta = new javax.swing.JTextArea();
        feedbackpic = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        iname = new javax.swing.JLabel();
        imsg = new javax.swing.JLabel();
        itextid = new javax.swing.JTextField();
        itextn = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        itexta = new javax.swing.JTextArea();
        isend = new javax.swing.JButton();
        icancel = new javax.swing.JButton();
        inquirypic = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        aid = new javax.swing.JLabel();
        apwd = new javax.swing.JLabel();
        atextid = new javax.swing.JTextField();
        atextp = new javax.swing.JPasswordField();
        asign = new javax.swing.JButton();
        acancel = new javax.swing.JButton();
        adminpic = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sid = new javax.swing.JLabel();
        spwd = new javax.swing.JLabel();
        stextf = new javax.swing.JTextField();
        spwdf = new javax.swing.JPasswordField();
        sin = new javax.swing.JButton();
        scancel = new javax.swing.JButton();
        srole = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        signinpic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rtextf = new javax.swing.JTextField();
        rpwdf = new javax.swing.JPasswordField();
        jComboBox2 = new javax.swing.JComboBox<>();
        rregister = new javax.swing.JButton();
        rreset = new javax.swing.JButton();
        rcancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 153));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\hp2.png")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 780, 270);

        jTabbedPane1.addTab("HOME", jPanel1);

        jPanel4.setLayout(null);

        fname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fname.setText("Enter Your Name");
        jPanel4.add(fname);
        fname.setBounds(41, 14, 136, 22);

        femail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        femail.setText("Enter Your Email");
        jPanel4.add(femail);
        femail.setBounds(40, 70, 136, 22);

        fback.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fback.setText("Enter FeedBack");
        jPanel4.add(fback);
        fback.setBounds(41, 160, 122, 22);

        fcancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fcancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\reset.png")); // NOI18N
        fcancel.setText("RESET");
        fcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcancelActionPerformed(evt);
            }
        });
        jPanel4.add(fcancel);
        fcancel.setBounds(260, 240, 160, 20);

        feedback.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        feedback.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\f.png")); // NOI18N
        feedback.setText("FEEDBACK");
        feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackActionPerformed(evt);
            }
        });
        jPanel4.add(feedback);
        feedback.setBounds(40, 240, 160, 20);

        ftextn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ftextn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftextnActionPerformed(evt);
            }
        });
        jPanel4.add(ftextn);
        ftextn.setBounds(286, 11, 213, 28);

        ftextm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ftextm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftextmActionPerformed(evt);
            }
        });
        jPanel4.add(ftextm);
        ftextm.setBounds(286, 67, 213, 28);

        ftexta.setColumns(20);
        ftexta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ftexta.setRows(5);
        jScrollPane1.setViewportView(ftexta);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(273, 133, 226, 91);

        feedbackpic.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\feedback form.jpg")); // NOI18N
        feedbackpic.setText("jLabel3");
        jPanel4.add(feedbackpic);
        feedbackpic.setBounds(0, 0, 590, 270);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\feedback.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(590, 0, 180, 180);

        jTabbedPane1.addTab("FEEDBACK", jPanel4);

        jPanel5.setLayout(null);

        id.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        id.setText("Enter Your ID");
        jPanel5.add(id);
        id.setBounds(45, 14, 253, 22);

        iname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        iname.setText("Enter Your Name");
        jPanel5.add(iname);
        iname.setBounds(40, 80, 253, 22);

        imsg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        imsg.setText("Enter Message");
        jPanel5.add(imsg);
        imsg.setBounds(50, 150, 153, 22);

        itextid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        itextid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itextidActionPerformed(evt);
            }
        });
        jPanel5.add(itextid);
        itextid.setBounds(328, 11, 181, 28);

        itextn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        itextn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itextnActionPerformed(evt);
            }
        });
        jPanel5.add(itextn);
        itextn.setBounds(330, 70, 181, 28);

        itexta.setColumns(20);
        itexta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        itexta.setRows(5);
        jScrollPane2.setViewportView(itexta);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(330, 130, 193, 91);

        isend.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        isend.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\send.png")); // NOI18N
        isend.setText("SEND");
        isend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isendActionPerformed(evt);
            }
        });
        jPanel5.add(isend);
        isend.setBounds(572, 42, 140, 31);

        icancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        icancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\reset.png")); // NOI18N
        icancel.setText("RESET");
        icancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icancelActionPerformed(evt);
            }
        });
        jPanel5.add(icancel);
        icancel.setBounds(575, 140, 140, 31);

        inquirypic.setForeground(new java.awt.Color(0, 0, 204));
        inquirypic.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\inquiry form.jpg")); // NOI18N
        inquirypic.setText("jLabel3");
        jPanel5.add(inquirypic);
        inquirypic.setBounds(0, 0, 780, 280);

        jTabbedPane1.addTab("INQUIRY FORM", jPanel5);

        jPanel7.setLayout(null);

        aid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        aid.setText("Enter Your ID");
        jPanel7.add(aid);
        aid.setBounds(58, 22, 111, 22);

        apwd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        apwd.setText("Enter Your Password");
        jPanel7.add(apwd);
        apwd.setBounds(58, 106, 164, 22);

        atextid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel7.add(atextid);
        atextid.setBounds(394, 19, 189, 28);

        atextp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        atextp.setText("111");
        jPanel7.add(atextp);
        atextp.setBounds(394, 103, 189, 28);

        asign.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        asign.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\login.png")); // NOI18N
        asign.setText("SIGN IN");
        asign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignActionPerformed(evt);
            }
        });
        jPanel7.add(asign);
        asign.setBounds(80, 190, 150, 30);

        acancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        acancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\reset.png")); // NOI18N
        acancel.setText("RESET");
        acancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acancelActionPerformed(evt);
            }
        });
        jPanel7.add(acancel);
        acancel.setBounds(330, 192, 160, 31);

        adminpic.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\admin.jpg")); // NOI18N
        adminpic.setText("jLabel3");
        jPanel7.add(adminpic);
        adminpic.setBounds(650, 0, 120, 160);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\bk.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(0, 0, 770, 280);

        jTabbedPane1.addTab("ADMIN", jPanel7);

        jPanel3.setLayout(null);

        sid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sid.setText("Enter Your ID");
        jPanel3.add(sid);
        sid.setBounds(50, 29, 164, 22);

        spwd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        spwd.setText("Enter Your Password");
        jPanel3.add(spwd);
        spwd.setBounds(50, 96, 164, 22);

        stextf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel3.add(stextf);
        stextf.setBounds(429, 26, 208, 28);

        spwdf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        spwdf.setText("111");
        jPanel3.add(spwdf);
        spwdf.setBounds(429, 93, 208, 28);

        sin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\login.png")); // NOI18N
        sin.setText("SIGN IN");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });
        jPanel3.add(sin);
        sin.setBounds(40, 210, 150, 33);

        scancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        scancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\reset.png")); // NOI18N
        scancel.setText("RESET");
        scancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scancelActionPerformed(evt);
            }
        });
        jPanel3.add(scancel);
        scancel.setBounds(270, 210, 160, 31);

        srole.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        srole.setText("Select Role");
        jPanel3.add(srole);
        srole.setBounds(50, 165, 164, 22);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "As A Donor", "As A Patient", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(429, 162, 208, 28);

        signinpic.setForeground(new java.awt.Color(51, 0, 204));
        signinpic.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\sign in 1.jpg")); // NOI18N
        signinpic.setText("jLabel3");
        jPanel3.add(signinpic);
        signinpic.setBounds(0, 0, 770, 280);

        jTabbedPane1.addTab("SIGN IN", jPanel3);

        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Your ID");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 40, 111, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Your Password");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 100, 164, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Select Role");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(70, 160, 86, 22);

        rtextf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rtextf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtextfActionPerformed(evt);
            }
        });
        jPanel2.add(rtextf);
        rtextf.setBounds(390, 40, 170, 28);

        rpwdf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rpwdf.setText("987");
        jPanel2.add(rpwdf);
        rpwdf.setBounds(391, 102, 170, 28);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "As A Donor", "As A Patient" }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(391, 173, 131, 28);

        rregister.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rregister.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\register sym.png")); // NOI18N
        rregister.setText("Register");
        rregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rregisterActionPerformed(evt);
            }
        });
        jPanel2.add(rregister);
        rregister.setBounds(72, 229, 170, 30);

        rreset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rreset.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\reset.png")); // NOI18N
        rreset.setText("Reset");
        rreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rresetActionPerformed(evt);
            }
        });
        jPanel2.add(rreset);
        rreset.setBounds(271, 229, 160, 31);

        rcancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rcancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\cancel.jpg")); // NOI18N
        rcancel.setText("Cancel");
        rcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcancelActionPerformed(evt);
            }
        });
        jPanel2.add(rcancel);
        rcancel.setBounds(460, 229, 160, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\sign in.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 770, 280);

        jTabbedPane1.addTab("REGISTER!!!", jPanel2);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel14)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel6);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 250, 780, 310);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\1_arNCqidepDKMH8T5B0d6kA.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 780, 230);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel10.setText("                                       H.K.B.K.BLOOD DONATION SYSTEM");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 780, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rcancelActionPerformed

    private void rresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rresetActionPerformed
        rtextf.setText(null);
        rpwdf.setText(null);
    }//GEN-LAST:event_rresetActionPerformed

    private void rregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rregisterActionPerformed
        try
        {
           
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/blood","root","");
            CallableStatement st=con.prepareCall("{CALL LOGIN(?,?,?)}");
            st.setInt(1, Integer.parseInt(rtextf.getText()));
            st.setString(2, rpwdf.getText());
            st.setString(3, String.valueOf(jComboBox2.getSelectedItem()));
            st.execute();
            JOptionPane.showMessageDialog(null,"Register Successfull");
            Registration r=new Registration();
          r.show();

    }//GEN-LAST:event_rregisterActionPerformed
catch (SQLException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void rtextfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtextfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtextfActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void scancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scancelActionPerformed
        stextf.setText(null);
        spwdf.setText(null);
    }//GEN-LAST:event_scancelActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        try
        {
            setID(stextf.getText());
            String sql="SELECT *FROM register WHERE Id=? AND Password=? AND Role=?";
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/blood","root","");
            PreparedStatement st=con.prepareStatement(sql);
            st.setInt(1, Integer.parseInt(stextf.getText()));
            st.setString(2, spwdf.getText());
            st.setString(3, String.valueOf(jComboBox1.getSelectedItem()));
            ResultSet rs=st.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this,"Sign in Successfull");
                if(jComboBox1.getSelectedIndex()==0)
                {
                    BloodDonor bd=new BloodDonor();
                   bd.show();
                }
                else
                {
                    BloodRecepient br=new BloodRecepient();
                   br.show();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Sign in Unsuccessful");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_sinActionPerformed

    private void acancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acancelActionPerformed
        atextid.setText(null);
        atextp.setText(null);
    }//GEN-LAST:event_acancelActionPerformed

    private void asignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignActionPerformed
        try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/blood","root","");
            PreparedStatement ps=con.prepareStatement("SELECT * FROM admin WHERE ID=? AND password=? ");
            ps.setString(1, atextid.getText());
            ps.setString(2, String.valueOf(atextp.getPassword()));
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this, "Admin Login Successful");

            }
            else
            {
                JOptionPane.showMessageDialog(this, "Admin Login Unsuccessful");
            }
        }       catch (SQLException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        Admin_access a=new Admin_access();
        a.show();

    }//GEN-LAST:event_asignActionPerformed

    private void icancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icancelActionPerformed
        itextid.setText(null);
        itextn.setText(null);
        
        itexta.setText(null);
    }//GEN-LAST:event_icancelActionPerformed

    private void isendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isendActionPerformed

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/blood","root","");
            String sql="INSERT INTO inquiryform values(?,?,?)";
            PreparedStatement st=con.prepareStatement(sql);
            st.setString(1, itextid.getText());
            st.setString(2, itextn.getText());
             st.setString(3, itexta.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inqiury sent");

        } catch (SQLException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_isendActionPerformed

    private void itextnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itextnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itextnActionPerformed

    private void itextidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itextidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itextidActionPerformed

    private void ftextmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftextmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftextmActionPerformed

    private void ftextnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftextnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftextnActionPerformed

    private void feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/blood","root","");
            String sql="INSERT INTO feedback values(?,?,?)";
            PreparedStatement st=con.prepareStatement(sql);
            st.setString(1, ftextn.getText());
            st.setString(2, ftextm.getText());
            st.setString(3, ftexta.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(null,"feedback sent");
        } catch (SQLException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_feedbackActionPerformed

    private void fcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcancelActionPerformed
        ftextn.setText(null);
        ftextm.setText(null);
        ftexta.setText(null);
    }//GEN-LAST:event_fcancelActionPerformed
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acancel;
    private javax.swing.JLabel adminpic;
    private javax.swing.JLabel aid;
    private javax.swing.JLabel apwd;
    private javax.swing.JButton asign;
    private javax.swing.JTextField atextid;
    private javax.swing.JPasswordField atextp;
    private javax.swing.JLabel fback;
    private javax.swing.JButton fcancel;
    private javax.swing.JButton feedback;
    private javax.swing.JLabel feedbackpic;
    private javax.swing.JLabel femail;
    private javax.swing.JLabel fname;
    private javax.swing.JTextArea ftexta;
    private javax.swing.JTextField ftextm;
    private javax.swing.JTextField ftextn;
    private javax.swing.JButton icancel;
    private javax.swing.JLabel id;
    private javax.swing.JLabel imsg;
    private javax.swing.JLabel iname;
    private javax.swing.JLabel inquirypic;
    private javax.swing.JButton isend;
    private javax.swing.JTextArea itexta;
    private javax.swing.JTextField itextid;
    private javax.swing.JTextField itextn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton rcancel;
    private javax.swing.JPasswordField rpwdf;
    private javax.swing.JButton rregister;
    private javax.swing.JButton rreset;
    private javax.swing.JTextField rtextf;
    private javax.swing.JButton scancel;
    private javax.swing.JLabel sid;
    private javax.swing.JLabel signinpic;
    private javax.swing.JButton sin;
    private javax.swing.JLabel spwd;
    private javax.swing.JPasswordField spwdf;
    private javax.swing.JLabel srole;
    private javax.swing.JTextField stextf;
    // End of variables declaration//GEN-END:variables
}
