/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bbms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aaliya
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        show_user();
    }
    public ArrayList<User> userlist()
    {
        ArrayList<User> userlist = new  ArrayList<>();
         try
    {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/blood","root","");
        String query="SELECT * FROM REGISTERFORM";
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery(query);
        User user;
        while(rs.next())
        {
            user=new User(rs.getString("fname"),rs.getInt("id"),rs.getString("gender"));
            userlist.add(user);  
        }
        
    }
     catch (SQLException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }    
         return userlist;
    }
    
    public void show_user()
    {
        ArrayList<User> list=userlist();
        DefaultTableModel model=(DefaultTableModel)Table1.getModel();
        Object[] row = new Object[3];
        for(int i=0;i<list.size();i++ )
        {
            row[0] = list.get(i).getname();
            row[1]=list.get(i).getid();
            row[2]=list.get(i).getgender();
            model.addRow(row);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rid = new javax.swing.JTextField();
        rname = new javax.swing.JTextField();
        rm = new javax.swing.JRadioButton();
        rf = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        rreset = new javax.swing.JButton();
        rcancel = new javax.swing.JButton();
        rinsert = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("                REGISTRATION FORM  ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-1, 0, 500, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Your ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 120, 126, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Your Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 150, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 200, 126, 22);

        rid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(rid);
        rid.setBounds(180, 120, 198, 28);

        rname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(rname);
        rname.setBounds(180, 60, 198, 28);

        buttonGroup1.add(rm);
        rm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rm.setSelected(true);
        rm.setText("Male");
        jPanel1.add(rm);
        rm.setBounds(180, 200, 61, 31);

        buttonGroup1.add(rf);
        rf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rf.setText("Female");
        jPanel1.add(rf);
        rf.setBounds(300, 200, 77, 31);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\reg page.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 40, 420, 240);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\reg.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 500, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 420, 280);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "fname", "id", "gender"
            }
        ));
        jScrollPane2.setViewportView(Table1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(430, 0, 510, 440);

        rreset.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        rreset.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\reset.png")); // NOI18N
        rreset.setText("Reset");
        rreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rresetActionPerformed(evt);
            }
        });
        getContentPane().add(rreset);
        rreset.setBounds(310, 290, 117, 30);

        rcancel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        rcancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\cancel.jpg")); // NOI18N
        rcancel.setText("Cancel");
        rcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcancelActionPerformed(evt);
            }
        });
        getContentPane().add(rcancel);
        rcancel.setBounds(310, 340, 117, 30);

        rinsert.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        rinsert.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaliya\\Documents\\project pics\\insert.png")); // NOI18N
        rinsert.setText("Insert Data");
        rinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rinsertActionPerformed(evt);
            }
        });
        getContentPane().add(rinsert);
        rinsert.setBounds(10, 290, 140, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rresetActionPerformed
        rid.setText(null);
        rname.setText(null);      
    }//GEN-LAST:event_rresetActionPerformed

    private void rcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcancelActionPerformed
     System.exit(0);
    }//GEN-LAST:event_rcancelActionPerformed

    private void rinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rinsertActionPerformed
    try
    {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/blood","root","");
            String sql="INSERT INTO registerform VALUES(?,?,?)";
                PreparedStatement st=con.prepareStatement(sql);
                 st.setString(1, rname.getText());
                st.setInt(2, Integer.parseInt(rid.getText()));
                String g = null;
                if(rm.isSelected())
                {
                    g=rm.getText();
                }
                if(rf.isSelected())
                {
                    g=rf.getText();
                }
                st.setString(3,g);
                
                st.executeUpdate();
                JOptionPane.showMessageDialog(null,"Registration Successfull");
    }//GEN-LAST:event_rinsertActionPerformed
catch (SQLException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton rcancel;
    private javax.swing.JRadioButton rf;
    private javax.swing.JTextField rid;
    private javax.swing.JButton rinsert;
    private javax.swing.JRadioButton rm;
    private javax.swing.JTextField rname;
    private javax.swing.JButton rreset;
    // End of variables declaration//GEN-END:variables
}
