/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane; 
import java.util.Calendar; 
import java.util.GregorianCalendar; 
import java.sql.CallableStatement;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
;


 

/**
 *
 * @author aastha
 */
public class login extends javax.swing.JInternalFrame {

  Connection conn=null; 
  ResultSet rs=null; 
  PreparedStatement pst=null; 
    public login() {
        initComponents(); 
         Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2); 
        
        currentDate(); 
        
       
    }
   
    public void currentDate(){ 
        Calendar cal=new GregorianCalendar(); 
        int month=cal.get(Calendar.MONTH); 
        int year=cal.get(Calendar.YEAR); 
        int day=cal.get(Calendar.DAY_OF_MONTH); 
         
         
        lbl_date.setText((month+1)+"/"+day+"/"+year);  
         
         
        int second=cal.get(Calendar.SECOND); 
        int minute=cal.get(Calendar.MINUTE); 
        int hour=cal.get(Calendar.HOUR); 
         
        lbl_time.setText(hour+":"+(minute)+":"+second); 
        
    }
     
   /* public void close() 
    { 
        WindowEvent winClosingEvent; 
      winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        lbl_date = new javax.swing.JMenu();
        lbl_time = new javax.swing.JMenu();

        setMinimumSize(new java.awt.Dimension(50, 50));

        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 120, 63, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 180, 60, 16);
        jPanel1.add(txt_username);
        txt_username.setBounds(210, 120, 130, 22);

        txt_password.setText("....");
        jPanel1.add(txt_password);
        txt_password.setBounds(210, 180, 38, 22);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 250, 77, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("LOGIN PAGE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 30, 153, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("PLEASE ENTER USERNAME AND PASSWORD");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 70, 311, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/images/IMG-20181022-WA0012.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 0, 670, 380);

        lbl_date.setText("DATE");
        jMenuBar1.add(lbl_date);

        lbl_time.setText("TIME");
        jMenuBar1.add(lbl_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        
    String Username=txt_username.getText(); 
    String password=txt_password.getText(); 
    try { 
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root",""); 
        String query="{CALL ADMINLOGIN(?,?,?)}"; 
        CallableStatement cs=con.prepareCall(query);  
        cs.setString(1,Username); 
        cs.setString(2,password); 
        cs.registerOutParameter(3,Types.INTEGER); 
   
        cs.execute(); 
        
        int count=cs.getInt(3);
        if(count==1) 
        { 
            JOptionPane.showMessageDialog(null,"login Successful!!!"+"\n"+"welcome hr"); 
            menuif mm=new menuif(); 
            this.getParent().add(mm); 
            mm.setVisible(true); 
            this.setVisible(false); 
            
        } 
        else 
        { 
            JOptionPane.showMessageDialog(null,"unsuccessful!!!"); 
            
        } 
    } catch(SQLException ex){ 
        Logger.getLogger(login.class.getName()).log(Level.SEVERE,null,ex); 
        
    }
          
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu lbl_date;
    private javax.swing.JMenu lbl_time;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
