/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Logins;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ADMIN
 */
public class Login_s extends javax.swing.JFrame {
      double[] i = new double[5];
      String modified;
      String stereo_system;
      String customized_detailing;
      String leather_interior;
      String Gps;
      String filename = null;
      byte[] person_image= null;
              
    
    /**
     * Creates new form Login_s
     */
    public Login_s() {
        initComponents();
        show_user();
       }
    
    displaycar_detail jtRowData = new displaycar_detail();
    displaycar_interior jtRowData1 = new displaycar_interior();
    displaypayment_detail jtRowData2 = new displaypayment_detail();
     
    public ArrayList<User> userList(){
        ArrayList<User> customersList = new ArrayList<>();
        try{
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb","root","");
             String query="SELECT * FROM customer";
             Statement st= con.createStatement();
             ResultSet rs= st.executeQuery(query);
             User user;
             while(rs.next()){
                 user=new User(rs.getInt("cust_id"), rs.getString("cust_name"), rs.getString("cust_address"), rs.getString("postcode"), rs.getString("telephone"), rs.getBytes("images"), rs.getString("date"));
                 customersList.add(user);
                 
             }
             
             }
        catch(Exception e){
            System.out.println(e);}
        return customersList;
    }
    public void show_user(){
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)jtableDisplay.getModel();
        Object[] row= new Object[6];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getcust_id();
            row[1]=list.get(i).getcust_name();
            row[2]=list.get(i).getcust_address();
            row[3]=list.get(i).getpostcode();
            row[4]=list.get(i).gettelephone();
            row[5]=list.get(i).getDate();
            model.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCModified = new javax.swing.JCheckBox();
        jCStereo = new javax.swing.JCheckBox();
        jCCustomized = new javax.swing.JCheckBox();
        jCLeather = new javax.swing.JCheckBox();
        jCGPS = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jCMile2 = new javax.swing.JComboBox();
        jtxtMile2 = new javax.swing.JTextField();
        jlblMile2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jCDistance = new javax.swing.JComboBox();
        jtxtDistance = new javax.swing.JTextField();
        jlblDistance = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jCchoose_a_car = new javax.swing.JComboBox();
        jCTradeIn = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblTradeIn = new javax.swing.JLabel();
        jlblchoose_a_car = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtxtTax = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubtotal = new javax.swing.JTextField();
        jdate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jtxtTelephone = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtPostcode = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jbtnInterior = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnImage = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableDisplay = new javax.swing.JTable();
        jlblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1370, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel14.setForeground(java.awt.Color.red);
        jLabel14.setText("Car Dealer System");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 450, 70));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCModified.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCModified.setText("Modified");
        jCModified.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCModifiedActionPerformed(evt);
            }
        });
        jPanel1.add(jCModified, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        jCStereo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCStereo.setText("Stereo System");
        jPanel1.add(jCStereo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jCCustomized.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCCustomized.setText("Customized Detailing");
        jPanel1.add(jCCustomized, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jCLeather.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCLeather.setText("Leather Interior");
        jPanel1.add(jCLeather, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jCGPS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCGPS.setText("Global Positioning System(GPS)");
        jPanel1.add(jCGPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 280, 170));

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jCMile2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCMile2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mile", "Kilometer", "Nautical Miles", " " }));
        jPanel14.add(jCMile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, 30));

        jtxtMile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMile2ActionPerformed(evt);
            }
        });
        jPanel14.add(jtxtMile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, 30));

        jlblMile2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel14.add(jlblMile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Convert");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 190, 170));

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jPanel22.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jCDistance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCDistance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Distance", "Speed", "Time", " " }));
        jPanel22.add(jCDistance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 30));
        jPanel22.add(jtxtDistance, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, 30));

        jlblDistance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel22.add(jlblDistance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Computer");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 30));

        getContentPane().add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 190, 170));

        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel28.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jPanel26.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jCchoose_a_car.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCchoose_a_car.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Make Selection", "Polo", "Golf", "BMW", "Porsche" }));
        jCchoose_a_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCchoose_a_carActionPerformed(evt);
            }
        });
        jPanel26.add(jCchoose_a_car, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jCTradeIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCTradeIn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00000", "50000", "100000", "200000", "400000" }));
        jCTradeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTradeInActionPerformed(evt);
            }
        });
        jPanel26.add(jCTradeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 110, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Choose a Car");
        jPanel26.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Trade In");
        jPanel26.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 70, 20));

        jlblTradeIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel26.add(jlblTradeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 110, 30));

        jlblchoose_a_car.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel26.add(jlblchoose_a_car, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 30));

        getContentPane().add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 330, 100));

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jPanel18.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tax Paid");
        jPanel18.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });
        jPanel18.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 140, 30));

        getContentPane().add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 340, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Total");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Sub Total");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 30));
        jPanel2.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 140, 30));
        jPanel2.add(jtxtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 140, 30));
        jPanel2.add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Date");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 94, 70, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 340, 140));

        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Telephone");
        jPanel30.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Name");
        jPanel30.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Address");
        jPanel30.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Post Code");
        jPanel30.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        jPanel30.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 290, 330));
        jPanel30.add(jtxtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 140, 30));
        jPanel30.add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 140, 30));
        jPanel30.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, 30));

        jtxtPostcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPostcodeActionPerformed(evt);
            }
        });
        jPanel30.add(jtxtPostcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 140, 30));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("Add payment details");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel30.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, 30));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("Add customer details");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel30.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, 30));

        jbtnInterior.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnInterior.setText("Add Interior details");
        jbtnInterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInteriorActionPerformed(evt);
            }
        });
        jPanel30.add(jbtnInterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Add car details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel30.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Display Interior Detail");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel30.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, 30));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setText("Display Car Details");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jPanel30.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 150, 30));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("Display Payment Detail");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jPanel30.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, 30));

        getContentPane().add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 550, 400));

        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel34.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jPanel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel36.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jPanel34.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 410));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel34.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 70, 30));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("Total");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel34.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 30));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel34.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 80, 30));

        jbtnDelete.setBackground(java.awt.Color.red);
        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel34.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 30));

        jbtnImage.setBackground(java.awt.Color.yellow);
        jbtnImage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnImage.setText("Choose");
        jbtnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImageActionPerformed(evt);
            }
        });
        jPanel34.add(jbtnImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, 30));

        jbtnUpdate.setBackground(java.awt.Color.green);
        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel34.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, 30));

        getContentPane().add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 330, 110));

        jtableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cust_id", "cust_name", "cust_address", "postcode", "telephone", "Date"
            }
        ));
        jtableDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableDisplayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtableDisplay);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 1040, 190));

        jlblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jlblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 470, 190, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jtxtMile2.setText("");
        jlblMile2.setText(null);
        jCMile2.setSelectedItem("Mile");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        double kilometer = 0.62137;
        double mile;
        double kilo;
        double Nautical;

        if(jCMile2.getSelectedItem().equals("Mile"))
        {
            mile = Double.parseDouble(jtxtMile2.getText());
            kilo = mile / kilometer;
            String sMile = String.format("%.2f",kilo);
            jlblMile2.setText(sMile + " km");
        }
        if(jCMile2.getSelectedItem().equals("Kilometer"))
        {
            mile = Double.parseDouble(jtxtMile2.getText());
            mile = mile * kilometer;
            String sMile = String.format("%.2f",mile);
            jlblMile2.setText(sMile + " Miles");
        }
        if(jCMile2.getSelectedItem().equals("Nautical Miles"))
        {
            mile = Double.parseDouble(jtxtMile2.getText());
            Nautical = mile / 1.5078;
            String sMile = String.format("%.2f",Nautical);
            jlblMile2.setText(sMile + " Knot");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jtxtDistance.setText("");
        jlblDistance.setText(null);
        jCDistance.setSelectedItem("Distance");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        double distance;
        double speed=100;
        double time=4.9;
        double iTime;

        if(jCDistance.getSelectedItem().equals("Distance"))
        {
            speed = Double.parseDouble(jtxtDistance.getText());
            distance = speed * time;
            String value = String.format("%.2f",distance);
            jlblDistance.setText(value);
        }
        if(jCDistance.getSelectedItem().equals("Time"))
        {
            distance = Double.parseDouble(jtxtDistance.getText());
            iTime = distance / speed;
            String value = String.format("%.2f",distance);
            jlblDistance.setText(value);
        }
        if(jCDistance.getSelectedItem().equals("Speed"))
        {
            distance = Double.parseDouble(jtxtDistance.getText());
            double iSpeed = distance / time;
            String value = String.format("%.2f",distance);
            jlblDistance.setText(value);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jCchoose_a_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCchoose_a_carActionPerformed
        double Polo = 15355;
        double Golf = 42568;
        double BMW = 56961;
        double Porsche = 99684;

        if (jCchoose_a_car.getSelectedItem().equals("Polo"))
        {
            String Car = String.format("%.2f",Polo);
            jlblchoose_a_car.setText(Car);
        }
        if (jCchoose_a_car.getSelectedItem().equals("Golf"))
        {
            String Car = String.format("%.2f",Golf);
            jlblchoose_a_car.setText(Car);
        }
        if (jCchoose_a_car.getSelectedItem().equals("BMW"))
        {
            String Car = String.format("%.2f",BMW);
            jlblchoose_a_car.setText(Car);
        }
        if (jCchoose_a_car.getSelectedItem().equals("Porsche"))
        {
            String Car = String.format("%.2f",Porsche);
            jlblchoose_a_car.setText(Car);
        }
        if (jCchoose_a_car.getSelectedItem().equals("Make Selection"))
        {
            jlblchoose_a_car.setText("");
        }
    }//GEN-LAST:event_jCchoose_a_carActionPerformed

    private void jCTradeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTradeInActionPerformed
        double trade0 = 0;
        double trade1 = 5000;
        double trade2 = 3000;
        double trade3 = 1500;
        double trade4 = 500;

        if (jCTradeIn.getSelectedItem().equals("00000"))
        {
            jlblTradeIn.setText("0");
        }
        if (jCTradeIn.getSelectedItem().equals("50000"))
        {
            String TradeInCar = String.format("%.2f",trade1);
            jlblTradeIn.setText(TradeInCar);
        }
        if (jCTradeIn.getSelectedItem().equals("100000"))
        {
            String TradeInCar = String.format("%.2f",trade2);
            jlblTradeIn.setText(TradeInCar);
        }
        if (jCTradeIn.getSelectedItem().equals("200000"))
        {
            String TradeInCar = String.format("%.2f",trade3);
            jlblTradeIn.setText(TradeInCar);
        }
        if (jCTradeIn.getSelectedItem().equals("400000"))
        {
            String TradeInCar = String.format("%.2f",trade4);
            jlblTradeIn.setText(TradeInCar);
        }
    }//GEN-LAST:event_jCTradeInActionPerformed

    private void jtxtPostcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPostcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPostcodeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFrame frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"confirm if you want to exit",
                "ATM systems",
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        double iStereo = 103.49;
        double Modified = 500.78;
        double Customized = 2000.49;
        double Leather = 1003.90;
        double GPS = 180.29;
        double AddAll;

        double iTax = 7.5;
        double Tax;
        double TradeIn = Double.parseDouble(jlblTradeIn.getText());
        double Choose_a_car = Double.parseDouble(jlblchoose_a_car.getText());

        jtxtSubtotal.setText("");
        jtxtTotal.setText("");

        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Polo")
                && (jCTradeIn.getSelectedItem().equals("00000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //=================================Golf-----------------------------------===============

        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Golf")
                && (jCTradeIn.getSelectedItem().equals("00000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //=====================================BMW----------------------======================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("BMW")
                && (jCTradeIn.getSelectedItem().equals("00000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //=======================================Porsche---------------------=================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Porsche")
                && (jCTradeIn.getSelectedItem().equals("00000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //=======================================50000 Mile=================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Polo")
                && (jCTradeIn.getSelectedItem().equals("50000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //====================================Golf========================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Golf")
                && (jCTradeIn.getSelectedItem().equals("50000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //=======================================BMW===================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("BMW")
                && (jCTradeIn.getSelectedItem().equals("50000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //======================================Porsche==================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Porsche")
                && (jCTradeIn.getSelectedItem().equals("50000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //========================================================================
        //==================================100000 Miles=========================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Polo")
                && (jCTradeIn.getSelectedItem().equals("100000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //====================================Golf=====================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Golf")
                && (jCTradeIn.getSelectedItem().equals("100000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //=========================BMW==============================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("BMW")
                && (jCTradeIn.getSelectedItem().equals("100000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //=====================================Porsche=================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Porsche")
                && (jCTradeIn.getSelectedItem().equals("100000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //===========================================================================
        //===================================================================================
        //==================================200000 Miles==================================================

        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Polo")
                && (jCTradeIn.getSelectedItem().equals("200000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //==============================Golf===================================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Golf")
                && (jCTradeIn.getSelectedItem().equals("200000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //================================BMW=====================================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("BMW")
                && (jCTradeIn.getSelectedItem().equals("200000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //=====================================Porsche========================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Porsche")
                && (jCTradeIn.getSelectedItem().equals("200000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //=========================================================================
        //===============================================================================
        //================================================================================================
        //==============================400000 Miles===========================================================

        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Polo")
                && (jCTradeIn.getSelectedItem().equals("400000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //================================Golf====================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Golf")
                && (jCTradeIn.getSelectedItem().equals("400000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //========================================BMW========================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("BMW")
                && (jCTradeIn.getSelectedItem().equals("400000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //===================================Porsche=========================================
        if (jCStereo.isSelected()&&jCCustomized.isSelected()&&jCModified.isSelected()
            &&jCLeather.isSelected()&& jCGPS.isSelected())
        {
            i[0] = iStereo;
            i[1] = Modified;
            i[2] = Customized;
            i[3] = Leather;
            i[4] = GPS;
            if(jCchoose_a_car.getSelectedItem().equals("Porsche")
                && (jCTradeIn.getSelectedItem().equals("400000")))
            {
                Choose_a_car = Choose_a_car - TradeIn;
                AddAll = Choose_a_car + i[0] + i[1] + i[2] + i[3] + i[4];

                Tax = (AddAll * iTax/100);
                String sTax = String.format("Rs %.2f",Tax);
                jtxtTax.setText(sTax);

                String SubTotal = String.format("Rs %.2f",AddAll);
                jtxtSubtotal.setText(SubTotal);

                String Total = String.format("Rs %.2f",AddAll + Tax);
                jtxtTotal.setText(Total);
            }
        }
        else
        {
            AddAll = Choose_a_car - TradeIn;
            String Total = String.format("Rs %.2f", AddAll);
            jtxtSubtotal.setText(Total);
            jtxtTotal.setText(Total);
        }
        //===================================Receipt==============================================
        String name = (jtxtName.getText());
        String address = (jtxtAddress.getText());
        String postcode = (jtxtPostcode.getText());
        String telephone = (jtxtTelephone.getText());
        String rTax = (jtxtTax.getText());
        String rSubTotal = (jtxtSubtotal.getText());
        String rTotal = (jtxtTotal.getText());
        String rTradeIn = (jlblTradeIn.getText());
        String rSoldCar = (jlblchoose_a_car.getText());

        jtxtReceipt.append("\tCar Dealer Systems:\n\n"
            +"Name:\t\t" + name
            +"\nAddress:\t\t" + address
            +"\nPostcode:\t\t" + postcode
            +"\nTelephone:\t\t" + telephone
            +"\nCost of car:\t\t" + rSoldCar
            +"\nTrade In:\t\t" + rTradeIn
            +"\nTax:\t\t" + rTax
            +"\nSub Total:\t\t" + rSubTotal
            +"\nTotal:\t\t" + rTotal
            +"\nTelephone:\t\t" + telephone
            +"\n\n\tThanks for car systems");

       
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jlblchoose_a_car.setText(null);
        jlblTradeIn.setText(null);
        jtxtSubtotal.setText(null);
        jtxtTotal.setText(null);
        jtxtTax.setText(null);
        jtxtMile2.setText(null);
        jtxtDistance.setText(null);
        jtxtName.setText(null);
        jtxtAddress.setText(null);
        jtxtPostcode.setText(null);
        jtxtTelephone.setText(null);
        jlblMile2.setText(null);
        jlblDistance.setText(null);
        jtxtReceipt.setText(null);
        jCchoose_a_car.setSelectedItem("Make Selection");
        jCTradeIn.setSelectedItem("00000");
        jCMile2.setSelectedItem("Mile");
        jCDistance.setSelectedItem("Distance");

        jCStereo.setSelected(false);
        jCModified.setSelected(false);
        jCCustomized.setSelected(false);
        jCLeather.setSelected(false);
        jCGPS.setSelected(false);
        jlblImage.setIcon(null);
        jdate.setDate(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jCModifiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCModifiedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCModifiedActionPerformed

    private void jtxtMile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMile2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMile2ActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb","root","");
             String query = "insert into car_detail(car_model, trade_in)values(?,?)";
             PreparedStatement pst = con.prepareStatement(query);
             String car_model;
             car_model=jCchoose_a_car.getSelectedItem().toString();
             pst.setString(1, car_model);
             String trade_in;
             trade_in=jCTradeIn.getSelectedItem().toString();
             pst.setString(2, trade_in);
              pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "inserted Sucessfully..!");
             
       }
       catch(Exception e){
            System.out.println(e);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnInteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInteriorActionPerformed
       try{
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb","root","");
             String query = "insert into car_interior(modified, stereo_system, customized_detailing, leather_interior, Gps)values(?,?,?,?,?)";
             PreparedStatement pst = con.prepareStatement(query);
             if(jCModified.isSelected()){
                 modified="500.78";
             }
             pst.setString(1, modified);
             if(jCStereo.isSelected()){
                 stereo_system="103.49";
             }
             pst.setString(2, stereo_system);
             if(jCCustomized.isSelected()){
                 customized_detailing="2000.49";
             }
             pst.setString(3, customized_detailing);
             if(jCLeather.isSelected()){
                 leather_interior="1003.90";
             }
             pst.setString(4, leather_interior);
             if(jCGPS.isSelected()){
                 Gps="180.29";
             }
             pst.setString(5, Gps);
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "inserted Sucessfully..!");
        }
        catch(Exception e){
            System.out.println(e);}

    }//GEN-LAST:event_jbtnInteriorActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         try{
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb","root","");
             String query="insert into payment(tax, subtotal, total)values(?,?,?)";
             PreparedStatement pst = con.prepareStatement(query);
             pst.setString(1, jtxtTax.getText());
             pst.setString(2, jtxtSubtotal.getText());
             pst.setString(3, jtxtTotal.getText());
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "inserted Sucessfully..!");
             
             
         }
          catch(Exception e){
            System.out.println(e);}

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try{
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb","root","");
             String query="insert into customer(cust_name, cust_address, postcode, telephone, images, date)values(?,?,?,?,?,?)";
             PreparedStatement pst = con.prepareStatement(query);
             pst.setString(1, jtxtName.getText());
             pst.setString(2, jtxtAddress.getText());
             pst.setString(3, jtxtPostcode.getText());
             pst.setString(4, jtxtTelephone.getText());
             pst.setBytes(5, person_image);
             SimpleDateFormat sdf = new SimpleDateFormat ("yyyy-MM-dd");
             String date = sdf.format(jdate.getDate());
             pst.setString(6, date);
             pst.executeUpdate();
             DefaultTableModel model = (DefaultTableModel)jtableDisplay.getModel();
             model.setRowCount(0);
             show_user();
             JOptionPane.showMessageDialog(null, "inserted Sucessfully..!");
             
             
         }
          catch(Exception e){
            System.out.println(e);}
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        int opt = JOptionPane.showConfirmDialog(null, "ARE YOU SURE TO DELETE", "DELETE", JOptionPane.YES_NO_OPTION);
        if(opt==0){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb","root","");
            int row = jtableDisplay.getSelectedRow();
            String value = (jtableDisplay.getModel().getValueAt(row, 0).toString());
            String query = "DELETE FROM customer WHERE cust_id="+value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jtableDisplay.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
         }
          catch(Exception e){
            System.out.println(e);}
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jtableDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableDisplayMouseClicked
        int i = jtableDisplay.getSelectedRow();
        TableModel model = jtableDisplay.getModel();
        
        jtxtName.setText(model.getValueAt(i,1).toString());
        jtxtAddress.setText(model.getValueAt(i,2).toString());
        jtxtPostcode.setText(model.getValueAt(i,3).toString());
        jtxtTelephone.setText(model.getValueAt(i,4).toString());
        byte[] img = (userList().get(i).getImage());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(jlblImage.getWidth(),jlblImage.getHeight(),Image.SCALE_SMOOTH));
        jlblImage.setIcon(imageIcon);
        try{
            int srow = jtableDisplay.getSelectedRow();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(srow,5));
            jdate.setDate(date);
        }
        catch(Exception e){
            System.out.println(e);}
        
        
        
        
        
    }//GEN-LAST:event_jtableDisplayMouseClicked

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb","root","");
            int row = jtableDisplay.getSelectedRow();
            String value = (jtableDisplay.getModel().getValueAt(row, 0).toString());
            String query="UPDATE customer SET cust_name=?, cust_address=?, postcode=?, telephone=?, images=?, date=? where cust_id="+value;
            PreparedStatement pst = con.prepareStatement(query);
             pst.setString(1, jtxtName.getText());
             pst.setString(2, jtxtAddress.getText());
             pst.setString(3, jtxtPostcode.getText());
             pst.setString(4, jtxtTelephone.getText());
             pst.setBytes(5, person_image);
             SimpleDateFormat sdf = new SimpleDateFormat ("yyyy-MM-dd");
             String date = sdf.format(jdate.getDate());
             pst.setString(6, date);
             pst.executeUpdate();
             DefaultTableModel model = (DefaultTableModel)jtableDisplay.getModel();
             model.setRowCount(0);
             show_user();
             JOptionPane.showMessageDialog(null, "Updated Sucessfully..!");
        }
        catch(Exception e){
            System.out.println(e);}
        
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(jlblImage.getWidth(),jlblImage.getHeight(),Image.SCALE_SMOOTH));
        jlblImage.setIcon(imageIcon);
        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum;(readNum=fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
                
            }
            person_image=bos.toByteArray();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jbtnImageActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jtRowData1.setVisible(true);
        jtRowData1.pack();

        jtRowData1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
         jtRowData.setVisible(true);
        jtRowData.pack();

        jtRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        jtRowData2.setVisible(true);
        jtRowData2.pack();

        jtRowData2.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_s().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCCustomized;
    private javax.swing.JComboBox jCDistance;
    private javax.swing.JCheckBox jCGPS;
    private javax.swing.JCheckBox jCLeather;
    private javax.swing.JComboBox jCMile2;
    private javax.swing.JCheckBox jCModified;
    private javax.swing.JCheckBox jCStereo;
    private javax.swing.JComboBox jCTradeIn;
    private javax.swing.JComboBox jCchoose_a_car;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnImage;
    private javax.swing.JButton jbtnInterior;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JLabel jlblDistance;
    private javax.swing.JLabel jlblImage;
    private javax.swing.JLabel jlblMile2;
    private javax.swing.JLabel jlblTradeIn;
    private javax.swing.JLabel jlblchoose_a_car;
    private javax.swing.JTable jtableDisplay;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtDistance;
    private javax.swing.JTextField jtxtMile2;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPostcode;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtSubtotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTelephone;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
